_target_: gpytorch.likelihoods.MultitaskGaussianLikelihood
_partial_: true
num_tasks: ${list_len:${target}}
noise_constraint:
  _target_: gpytorch.constraints.Interval
  lower_bound: ${likelihood_noise_lower}
  upper_bound: ${likelihood_noise_upper}
