name: '{model.class}-{target}-{hash}'

data:
  training:
    func: pandas.read_parquet
    path: ../data/training/training_data-k1500-pamir_ns180-expX.parquet
    engine: pyarrow
  inference:
    func: xarray.open_zarr
    store: ../data/inference/inference_variables-710w365s750e400n-100m.zarr

target: permafrost_temperature
features:
- altitude
- slope_angle
- aspect_sin
- aspect_cos
- surface_index
- albedo
- emissivity
- temperature
- precipitation
- snow_melt_doy
- temp2m_DJF_q05
- temp2m_JJA_q05
- temp2m_MAM_q05
- temp2m_SON_q05
- temp2m_DJF_q50
- temp2m_JJA_q50
- temp2m_MAM_q50
- temp2m_SON_q50
- temp2m_DJF_q95
- temp2m_JJA_q95
- temp2m_MAM_q95
- temp2m_SON_q95
- precip_DJF_q50
- precip_JJA_q50
- precip_MAM_q50
- precip_SON_q50
- precip_DJF_q95
- precip_JJA_q95
- precip_MAM_q95
- precip_SON_q95

scalers:
  features:
    class: pamir_mlpermafrost.preprocessing.scalers.StandardScaler_toTensor
    skip_columns: [ 4 ] # Skip the categorical index column (sets µ=0, σ=1)
  target:
    class: pamir_mlpermafrost.preprocessing.scalers.StandardScaler_toTensor
    skip_columns: [] # No columns to skip for target

device: cpu
model:
  class: pamir_mlpermafrost.models.gp.models.GPMixedMeanCatIndex
  likelihood:
    class: gpytorch.likelihoods.GaussianLikelihood
  linear_mean_idx: [ 0, 8 ]
  cat_idx: [ 4 ]

training:
  learning_rate: 0.02
  n_iters: 500
  tolerance: 0.005
  patience: 5

inference:
  chunks:
    x: 300
    y: 300
