#
# ( Poly + RBF ) * Index
_target_: gpytorch.kernels.ProductKernel
_partial_: true
_args_:
- _target_: gpytorch.kernels.AdditiveKernel
  _args_:
  - _target_: gpytorch.kernels.PolynomialKernel
    power: 1
    active_dims: ${idx_linear}
    offset_prior:
      _target_: gpytorch.priors.NormalPrior
      loc: 0.0
      scale: 1.0
  - _target_: gpytorch.kernels.ScaleKernel
    base_kernel:
      _target_: gpytorch.kernels.RBFKernel
      active_dims: ${idx_rbf}
      ard_num_dims: ${num_rbf}
      lengthscale_prior:
        _target_: gpytorch.priors.GammaPrior
        concentration: 2.0
        rate: 1.0
      # ard_num_dims must equal length of active_dims (numeric features)
- _target_: gpytorch.kernels.IndexKernel
  num_tasks: ${num_categories}
  active_dims: ${idx_categorical}
  rank: 1
  var_constraint: 
    _target_: gpytorch.constraints.GreaterThan
    lower_bound: 1e-5
